version: '3'

services:
  qwetle:
    container_name: qwetle
    build:
      context: .
      dockerfile: ./app/Dockerfile
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - $USERDIR/projects/Qwetle/src:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.qwetle-rtr.entrypoints=https"
      - "traefik.http.routers.qwetle-rtr.rule=Host(`$DOMAIN_NAME`,`www.$DOMAIN_NAME`)"
      ## HTTP Services
      - "traefik.http.routers.qwetle-rtr.service=qwetle-svc"
      - "traefik.http.services.qwetle-svc.loadbalancer.server.port=80"